version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      MONGODB_URL: "mongodb://mongo_user:mongo_password@mongodb:27017/"
      SECRET_KEY: "YOUR_SUPER_SECRET_KEY_HERE_REPLACE_THIS_WITH_A_LONG_RANDOM_STRING"
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      REDIS_URL: redis://redis:6379/0
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SENDER_EMAIL: noreply@yourdomain.com

    depends_on:
      - mongodb
      - redis
      - mailhog
    
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
      MONGO_INITDB_DATABASE: mydatabase
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    logging:
      driver: "none" 

volumes:
  mongo_data:
  redis_data: